---
title: "IFCD0210 Init Mail"
categories: [ifcd0210, training]
---

## Content

1. No és un curs llarg, ni de broma, des del primer dia, a treballar.

2. Mooc Helsinki Java
    - `https://java-programming.mooc.fi/`, 
    - la primera part Java Programming I, és fonamental fer-la aquesta setmana o durant aquestes dos primeres setmanes de curss o màxim, màxim durant les vacances de Nadal.
    - ja sabeu: algoritmica bàsica i POO
3. La nostra web: `https://albertprofe.github.io/web/`
    - ja la podeu putijejar
    - encara no te domini propi: ho tindrà
    - feta amb quarto/markdown/github-pages: `https://albertprofe.github.io/web/about/aboutthissite.html` (ja ho explicaré a classe)
4. Comptes que necessitareu:
    - GitHub
    - Oracle (per descarregar Java)
    - MongoDB
    - AWS (demana credit card)
5. IDEs:
    - Visual Code per ReactJS
    - IntellJIdea per Java Spring Boot
    - Sublime
6. OS, linux virtual machine? dual?  ho parlem però mireu-vos això
    - `https://neverinstall.com/` (i feu-vos un compte)
7. per qui no pugui vindre dilluns vinent, URL del jit si meet:
    - `https://meet.jit.si/cifoweb`
    - `https://meet.jit.si/cifowebboard`
    
    
<!--- navLinks -->
<br><br>
<div class=row>
<br>
<div class='column left previous'>
<br>
[{{< fa solid arrow-left >}} IFCD0210 Calendar](/ifcd0210/ifcd0210calendar.qmd)
<br>
</div>
<br>
<div class='column center'>
<br>
[{{< fa solid arrow-up >}} top](#top)
<br>
</div>
<br>
<div class='column right next'>
<br>
[IFCD Deliveries  {{< fa solid arrow-right >}}](/ifcd0210/ifcd0210deliveries.qmd)
<br>
</div>
<br>
</div>
