---
title: "IFCD0210 Bakclog Course"
categories: [ifcd0210, backlog]
---

::: {.summary}

- [December 2022](/ifcd0210/ifcd0210backlog.qmd#december-2022)
- [January 2023](/ifcd0210/ifcd0210backlog.qmd#djanuary-2023)
- [February 2023](/ifcd0210/ifcd0210backlog.qmd#february-2023)
- [March 2023](/ifcd0210/ifcd0210backlog.qmd#marh-2023)
- [April 2023](/ifcd0210/ifcd0210backlog.qmd#april-2023)
- [May 2023](/ifcd0210/ifcd0210backlog.qmd#may-2023)
- [June 2023](/ifcd0210/ifcd0210backlog.qmd#june-2023)
- [July 2023](/ifcd0210/ifcd0210backlog.qmd#julu-2023)

:::

## January 2023

::: {.column-page-right}
| Week  | Day | Date | Topics |  Details Topics |
| -- | -- | -- | -- | -- |
| 3 | 10 | 09/01/2023 | Differenct approaches to complex problems are crucial to solve it - How to manage large volumes: quarto | Bash, Pipes, How to stay in class: connect |
|  | 11 | 10/01/2023 | How to create a Maven Java Project with TDD in Mind - What could go wrong when create a Maven Project | TDD, JUnit, Maven Java|
|  | 12 | 11/01/2023 | What is Model in Java - Why is so important - All begins in Model | Java Classes and Objects |
|  | 13 | 12/01/2023 | Coupling and DD defines even Deploy - Plan a Project - Even name a variable is important | Coupling Lab#SE02-4 |
|  | 14 | 13/01/2023 | Time Management -  Object Creation - Nested objects are not easy - Tags & Little-cube are our friends | Nested Objects in Java Lab#SE02-1 |
| 4 | 15 | 16/01/2023 | - | - |
|  | 16 | 17/01/2023 | - | - |
|  | 17 | 18/01/2023 | - | - |
|  | 18 | 19/01/2023 | - | - |
|  | 19 | 20/01/2023 | - | - |
| 5 | 20 | 23/01/2023 | - | - |
|  | 21 | 24/01/2023 | - | - |
|  | 22 | 25/01/2023 | - | - |
|  | 23 | 26/01/2023 | - | - |
|  | 24 | 27/01/2023 | - | - |
| 6 | 25 | 30/01/2023 | - | - |
|  | 26 | 31/01/2023 | - | - |
|  | 27 | 01/02/2023 | - | - |
|  | 28 | 02/02/2023 | - | - |
|  | 29 | 03/02/2023 | - | - |
: Backlog course January 2023 table {tbl-colwidths="[4,4,10,45,27]"}
:::

## February 2023

::: {.column-page-right}
| Week  | Day | Date | Topics |  Details Topics |
| -- | -- | -- | -- | -- |
| 7 | 30 | 06/02/2023 | - | - |
|  | 31 | 07/02/2023 | - | - |
|  | 32 | 08/02/2023 | - | - |
|  | 33 | 09/02/2023 | - | - |
|  | 34 | 10/02/2023 | - | - |
: Backlog course February 2023 table {tbl-colwidths="[4,4,10,45,27]"}
:::

## March 2023

## April 2023

## May 2023

## June 2023

## July 2023



## December 2022

::: {.column-page-right}
| Week  | Day | Date | Topics |  Details Topics |
| -- | -- | -- | -- | -- |
| 1 | 1 | 12/12/2022 | Introduction to course IFCD0210 - Setting of all tools we are going to need | - |
|  | 2 | 13/12/2022 | Quarto create and Publish in GitHub - Create VM and IDEs - Accounts - MOOC | - |
|  | 3 | 14/12/2022 | Linux VM VirtualBox over Windows - What is a Dependency Management, Maven | - |
|  | 4 | 15/12/2022 | Quarto create and Publish in GitHub with adavnced tools | - |
|  | 5 | 16/12/2022 | Create Java Maven Project: JUnit - What is Java SE, EE and Spring MVC, Boot - Create classes| - |
| 2 | 6 | 19/12/2022 | Create Java Maven Project: Git - Why scope is so important in Java | - |
|  | 7 | 20/12/2022 | Introduction to MVC Pattern | - |
|  | 8 | 21/12/2022 | Create Java Maven Project: Classes - Tag & Little-Cube are our dear friends | - |
|  | 9 | 22/12/2022 | Introduction to React JS Framework | - |
: Backlog course December 2022 table {tbl-colwidths="[4,4,10,45,27]"}
:::

<!--- navLinks -->
<br><br>
<div class=row>
<br>
<div class='column left previous'>
<br>
[{{< fa solid arrow-left >}} IFCD Init Mail](/ifcd0210/ifcd0210initemail.qmd)
<br>
</div>
<br>
<div class='column center'>
<br>
[{{< fa solid arrow-up >}} top](#top)
<br>
</div>
<br>
<div class='column right next'>
<br>
[About me {{< fa solid arrow-right >}}](/about/about-this-me.qmd)
<br>
</div>
<br>
</div>
